### PR TITLE
rss: ingest atom/rss feed contents already decoding HTML special chars

### PR DESCRIPTION
**Pull request by glima**
Without this move, the main UI could show info and feed entries with crude HTML marks, as in "&#8220". Translating that at the source is the best move, since they get stored right in the DB.

### CODE REVIEW

**Comment by glima** [comment]
Ping?

**Comment by ckampfe** [comment]
I think this makes sense. I'm trying to test this.

**Comment by ckampfe** [comment]
@glima do you have an example of an RSS feed that exhibits this behavior that I can test?

**Comment by glima** [comment]
Yes, try https://kottke.org/

**Comment by ckampfe** [comment]
Yep, I think this makes sense and seems to work. Let's give it a shot. Thank you for the contribution @glima!

**Pull request merged**
