### PR TITLE
Open link in browser feature

### PR DESCRIPTION
**Pull request by Funami580**
In my opinion a useful feature, what do you think?

### CODE REVIEW

**Comment by ckampfe** [comment]
Hi @Funami580 , thank you for your pull requests. I will try to look at this PR and https://github.com/ckampfe/russ/pull/3 soon. Thank you!

**Comment by ckampfe** [comment]
Hi again @Funami580, I finally got a chance to look at this, thank you for the PR.

I noticed that the webbrowser library is specified as:

```
webbrowser = { git = "https://github.com/codota/webbrowser-rs", branch = "feature/add-suppress-output-flag-with-docs" }
```
which appears to be a fork of the mainline https://crates.io/crates/webbrowser dependency.

What made you use a fork (`codota/webbrowser-rs`) vs the mainline (`amodm/webbrowser-rs`)? Also, what is this specific branch? I am not familiar with `webbrowser-rs` in general, so I would like to understand the context here. Thank you.

**Comment by Funami580** [comment]
The problem with the original crate was that it redirected the output of external commands to stdout. This interfered with the russ TUI. See: https://github.com/amodm/webbrowser-rs/issues/20

**Comment by ckampfe** [comment]
@Funami580 Great, thanks for the explanation. We will have to keep an eye on that functionality in the future to see if the mainline browser crate merges the silent mode PR. Otherwise, this seems good to go, I'm going to merge it. Thanks again for your contribution, I appreciate it.

**Pull request merged**
